export const ASSETS = {
  walkthroughImage: require('../pictures/walkthrough.jpg'),
  chevronLeft: require('../pictures/left-chevron.png'),
  chevronRight: require('../pictures/right-chevron.png'),
  defaultAvatarImage: require('../pictures/adduser.png'),
  avatar: require('../pictures/defaultAvatar.png'),
  contacts: require('../pictures/contacts.png'),
  contactsActive: require('../pictures/contacts-active.png'),
  chats: require('../pictures/chats.png'),
  chatsActive: require('../pictures/chats-active.png'),
  more: require('../pictures/options.png'),
  moreActive: require('../pictures/options-active.png'),
  plus: require('../pictures/plus.png'),
  women1: require('../pictures/women1.jpg'),
  women2: require('../pictures/women2.jpg'),
  guy: require('../pictures/guy.jpg'),
  male: require('../pictures/male.jpg'),
};
